### ISSUE TITLE
Firmware baseline update causes OS Volume to be deleted.

### ISSUE THREAD

**Issue by bryansullins** [HewlettPackard/oneview-ansible-collection#98] opened 2021-04-23 19:13 UTC
When I use the oneview_server_profile to create a new Server Profile, then attempt to update the firmware baseline, instead of staging the firmware, OneView will warn that:

"Changing the OS deployment settings for the profile will cause the OS volume . . . to be deleted."

As far as I know this is not intended?

I was directed here by HPE Support. I would like to contact you directly for more info? Thank you!

![HPEFirmwareUpdateIssue](https://user-images.githubusercontent.com/40724324/115919033-22d80c80-a42d-11eb-81c8-05270ad16762.jpg)

**Comment by VenkateshRavula** [comment] 2021-04-27 07:55
Hi @bryansullins , Can you please share the playbook you have used to create server profile.

**Comment by bryansullins** [comment] 2021-04-27 22:11
Venkatesh,

I would be happy to, however, are you part of the HPE organization?

We'd like to see if this is under our NDA with HPE.

And, if I share it, it will have to be through email and not on github
since it does have datacenter hostnames.

Thanks!

Bryan

**Comment by VenkateshRavula** [comment] 2021-04-28 05:12
Hi @bryansullins, I am a part of HPE organization. You can share the requested playbook via email to venkatesh.ravula@hpe.com

**Comment by VenkateshRavula** [comment] 2021-05-10 09:58
Hi @bryansullins, Thanks for sharing the playbook. I have used the playbook to reproduce the issue but not able to reproduce it. Everything worked as expected for me. Can you share some more info briefly (step by step) to help us reproduce the issue.

**Comment by VenkateshRavula** [comment] 2021-05-31 06:56
The issue needs 2 fixes in user's playbook file.
- ```Management.networkuri``` should be lower case in server profile os custom attributes
- The connection networkuris in ```server profile template``` and ```server profile``` are swapped and hence the json structure is unstable. So whenever user tries to edit the profile from browser, then it tries to correct the networkuris from the UI and shows the os volume delete and recreate warning message.

The issue got resolved when user made the above 2 modifications to his playbook. So we are closing the issue.

**Closed by VenkateshRavula** 2021-05-31 06:56 UTC
