### ISSUE TITLE
assign static IP addresses during LE creation

### ISSUE THREAD

**Issue by pwojtyra** [HewlettPackard/oneview-ansible-collection#86] opened 2021-03-29 11:05 UTC
Is there any way to assign static IP addresses to the enclosure devices (network modules and iLOs) in a tasks that creates LE? This feature is in GUI in section "IPv4 Addresses" during LE creation and is available starting from OV 5.3 or 5.4.

**Comment by VenkateshRavula** [comment] 2021-04-05 06:29
This seems like a duplicate of below issue. Please have a look if that helps.
https://github.com/HewlettPackard/oneview-ansible/issues/619

**Comment by VenkateshRavula** [comment] 2021-04-09 05:30
We are closing this issue considering it as a duplicate of an ansible issue (https://github.com/HewlettPackard/oneview-ansible/issues/619). please feel free to reopen if the above provided solution doesn't help.

**Closed by VenkateshRavula** 2021-04-09 05:30 UTC
Labels: duplicate, help wanted

**Comment by vinicole** [comment] 2022-09-15 14:05
Hello,

This seems indeed a duplicate of https://github.com/HewlettPackard/oneview-ansible/issues/619
However using the code proposed in issue #619 now returns the following error with oneview-ansible-collection:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: hpeOneView.exceptions.HPEOneViewException: ('The JSON cannot be mapped to array or collection.', {'errorCode': 'INVALID_NESTED_JSON_ELEMENT', 'message': 'The JSON cannot be mapped to array or collection.', 'details': 'The nested JSON "enclosureBaySettings" sent in the request is not a valid array or collection.', 'messageParameters': [], 'recommendedActions': ['Correct the JSON as appropriate array or collection and retry the request.'], 'errorSource': None, 'nestedErrors': [], 'data': {}})

RHEL 8.6
Python 3.6.8
Ansible 2.9.27
Oneview-ansible-collection 7.2.0

Could you please have a look?

Thanks,
V
